language: node_js
node_js:
  - node

before_install:
- npm install -g npm@latest

script: 
- set -e
- npm run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master