language: node_js
node_js:
  - node

cache: npm

script: 
- set -e
- mkdir dist
- npm run build

before_deploy:
- ls dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: zhaoweicheng98.github.io/Agileffy/
  local_dir: dist
  on:
    branch: master