language: node_js
node_js:
  - lts/*
  
dist: xenial
  
cache: npm

script: 
- set -e
- mkdir dist
- npm run build
- npm run test:unit

after_success:


before_deploy:
- ls dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: agileffy.github.io
  repo: agileffy/agileffy.github.io
  target_branch: master
  local_dir: dist
  on:
    branch: master
